FROM sirisurab/tp-jup-app-pkgs AS app
ARG SSH_PRIVATE_KEY
ARG SSH_PUB_KEY
ARG SSH_KEY_PASSPHRASE
USER root
RUN rm -Rf /app && \
mkdir /app && \
chmod -R 777 /app && \
mkdir -p /root/.ssh && \
echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa && \
echo "${SSH_PUB_KEY}" > /root/.ssh/id_rsa.pub && \
chmod -R 400 /root/.ssh/ && \
ssh-keyscan github.com > /root/.ssh/known_hosts && \
eval $(ssh-agent -s) && \
printf "${SSH_KEY_PASSPHRASE}\n" | ssh-add /root/.ssh/id_rsa && \
git clone -v "ssh://git@github.com/sirisurab/transpred.git" /app
# Set the working directory to /app
WORKDIR /app
ENV PYTHONPATH="/app/src:${PYTHONPATH}"