# to be tagged as sirisurab/tp-jup-base

# Use an official Python runtime as a parent image

FROM jupyter/minimal-notebook AS base
USER root
RUN mkdir app
# this is for geopandas
RUN apt-get update && \
apt-get -y install  curl \
                    g++  \
                    make \
                    unzip && \
curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz && \
cd spatialindex-src-1.8.5 && \
./configure && \
make && \
make install && \
ldconfig

# to be tagged as sirisurab/tp-jup-beefy-base
FROM base AS beefy-base

RUN apt-get update && \
# for matplotlib
apt-get -y install  libfreetype6-dev \
                    pkg-config \
# ssh only needed for the jupyter-notebook version
                    ssh \
# for redis-cli
                    redis-tools && \
mkdir /minio && \
wget -P /minio/ https://dl.minio.io/client/mc/release/linux-amd64/mc && \
chmod -R +x /minio && \
apt-get -y install libsnappy-dev

# to be tagged as sirisurab/tp-jup-app-pkgs
FROM beefy-base AS app-pkgs

COPY ./environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml
RUN ["/bin/bash","-c","source activate transpred"]
ENV PATH="/minio:/opt/conda/envs/transpred/bin:${PATH}"