# to be tagged as sirisurab/tp-base

# Use an official Python runtime as a parent image

FROM continuumio/miniconda3 AS base

RUN mkdir app
# this is for geopandas
RUN apt-get update && \
apt-get -y install  curl \
                    g++  \
                    make \
                    unzip && \
curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz && \
cd spatialindex-src-1.8.5 && \
./configure && \
make && \
make install && \
ldconfig




FROM base AS beefy-base

#RUN apt-get update && \
#apt-get -y install  apt-transport-https \
#                    ca-certificates \
#                    gnupg2 \
#                    software-properties-common && \
#curl -fsSL https://download.docker.com/linux/debian/gpg | \
#apt-key add - && \
#add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
#apt-get update && \
#apt-get -y install docker-ce
#RUN bash service docker start

RUN apt-get update && \
# for matplotlib
apt-get -y install  libfreetype6-dev \
                    pkg-config \
# for redis-cli
                    redis-tools && \
mkdir /minio && \
wget -P /minio/ https://dl.minio.io/client/mc/release/linux-amd64/mc && \
chmod -R +x /minio && \
# configure mc
#/minio/mc config host add --insecure minio http://minio:9000 minio minio123 && \
# for fastparquet
pip install numpy

# copy minio config file
COPY  ./secret/config.json $HOME/.mc/
ENV PATH="/minio:${PATH}"


# to be tagged as sirisurab/tp-app-pkgs

FROM beefy-base AS app-pkgs

# Install any needed packages specified in requirements_1.txt
COPY ./requirements_1.txt /app/requirements_1.txt
COPY ./requirements_2.txt /app/requirements_2.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements_1.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements_2.txt
